package com.herasgarden.gardencore.api.integration;

/**
 * Durable cross-service events written by GardenCore/domain plugins and
 * consumed by integrations such as Iris.
 */
public enum IntegrationEventType {
    TERRITORY_APPLICATION_SUBMITTED,
    TERRITORY_APPLICATION_APPROVED,
    TERRITORY_APPLICATION_REJECTED,
    TERRITORY_CREATED,
    TERRITORY_DELETED,
    CITIZEN_AFFILIATION_CHANGED,
    GOVERNMENT_CREATED,
    GOVERNMENT_ROLE_CHANGED,
    CITIZENSHIP_APPLICATION_SUBMITTED,
    CITIZENSHIP_APPLICATION_REVIEWED,
    TREASURY_CHANGED,
    PAYROLL_COMPLETED,
    PAYROLL_FAILED,
    PROPERTY_SOLD,
    PROPERTY_RENTED,
    MAIL_DELIVERED,
    MAIL_DELIVERY_FAILED,
    TRADE_CONTRACT_CHANGED,
    EVENT_ANNOUNCEMENT,
    EVENT_CANCELLED,
    TICKET_PURCHASED,
    TICKET_REFUNDED,
    TICKET_ADMITTED,

    BUG_REPORT_SUBMITTED,
    PLAYER_REPORT_SUBMITTED,
    STAFF_ALERT,
    SERVER_STARTED,
    SERVER_STOPPING,
    PLAYER_JOINED,
    PLAYER_LEFT,
    MINECRAFT_XP_EARNED,
    MODERATION_ACTION_APPLIED,
    MODERATION_ACTION_REVOKED,
    MODERATION_COMMAND_FAILED
}
